root: ../test
task: str
download_links:
  # IC13_857
  - https://drive.usercontent.google.com/download?id=1PZSCbe6_DI8MlCqCRWXGT2PP92_frIXq&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1qkN7NDg0zUHxUiZHAeEatDTqlsgpFWp3&authuser=0&confirm=t
  # IC15_2077
  - https://drive.usercontent.google.com/download?id=1dFkY3DNbr-Mepn3TWBiA9COEJ63fGFcp&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1UvVwLNZ3tS1YdTBa8MulPzjeVezKaDro&authuser=0&confirm=t
  # SVTP
  - https://drive.usercontent.google.com/download?id=1aofeerilxJ7J3S7QxuCEXbmXTpz8Xshx&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1rJ1KoO4K_VUxEAUN_bMgBGzK8_JZAAno&authuser=0&confirm=t
  # IIIT5k
  - https://drive.usercontent.google.com/download?id=1XFO2M1Kbgwv3-iTNTmhQXAEjNmKYOeoT&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1stwK2hFsyaV7HHsEG9EYgnUQebNb2_nG&authuser=0&confirm=t
  # COCOv1.4
  - https://drive.usercontent.google.com/download?id=1Se2QSGS19xx7Gfy-SUdX9mlAOr2eYsfA&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1xvekFi389QfkH7yS0JIVV0QzjhUspjDv&authuser=0&confirm=t
  # IC15_1811
  - https://drive.usercontent.google.com/download?id=1pHsw8wrThD9EGEE6AusQLZozefSj4iyR&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1TXZ1qHuKAksaAlvd3qMv4IHKnN-IJW9a&authuser=0&confirm=t
  # Uber
  - https://drive.usercontent.google.com/download?id=1L2j6BZeLTGQ1FIl8HB_D3AFiWLltGV5r&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=12DUj28yzLWxFO_gfMfSjTkRujYD5MNEE&authuser=0&confirm=t
  # IC13_1095
  - https://drive.usercontent.google.com/download?id=1fu8onMt3Z6fDLNAiHcm-sQ2qCXduE-FU&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1OQAZtLj8U2Cl4L0ErGFsz6vGIVTTWasD&authuser=0&confirm=t
  # IC13_1015
  - https://drive.usercontent.google.com/download?id=1mbsfuvWB282HYfn9tbqcj1nUDkLXcSNB&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1QGogU_hV-oN7iY2POutdD2LDcmK6plnV&authuser=0&confirm=t
  # ArT
  - https://drive.usercontent.google.com/download?id=1-53knSy-uTSngCG7wyBngVyTuTCmdnWl&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=172EsSaf7BVaB1ORtohi-Jc_8SuUKZGGf&authuser=0&confirm=t
  # SVT
  - https://drive.usercontent.google.com/download?id=1p7aVUr9Yr7c4X4YUBvk2-YP28rraHjn9&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1ALmhvSleZ0yf-lcdbQPP3M9Zc3oqnXij&authuser=0&confirm=t
  # CUTE80  
  - https://drive.usercontent.google.com/download?id=1Ujr4axHKnu54P2rIGUhkjdM6XlhDYrI_&authuser=0&confirm=t
  - https://drive.usercontent.google.com/download?id=1DvZi9L3MqjO2zRUyCg3YvP4qMAt2bsme&authuser=0&confirm=t
filenames: 
  # IC13_857
  - ../test/IC13_857/data.mdb
  - ../test/IC13_857/lock.mdb
  # IC15_2077
  - ../test/IC15_2077/data.mdb
  - ../test/IC15_2077/lock.mdb
  # SVTP
  - ../test/SVTP/data.mdb
  - ../test/SVTP/lock.mdb
  # IIIT5k
  - ../test/IIIT5k/data.mdb
  - ../test/IIIT5k/lock.mdb
  # COCOv1.4
  - ../test/COCOv1.4/data.mdb
  - ../test/COCOv1.4/lock.mdb
  # IC15_1811
  - ../test/IC15_1811/data.mdb
  - ../test/IC15_1811/lock.mdb
  # Uber
  - ../test/Uber/data.mdb
  - ../test/Uber/lock.mdb
  # IC13_1095
  - ../test/IC13_1095/data.mdb
  - ../test/IC13_1095/lock.mdb
  # IC13_1015
  - ../test/IC13_1015/data.mdb
  - ../test/IC13_1015/lock.mdb
  # ArT
  - ../test/ArT/data.mdb
  - ../test/ArT/lock.mdb
  # SVT
  - ../test/SVT/data.mdb
  - ../test/SVT/lock.mdb
  # CUTE80
  - ../test/CUTE80/data.mdb
  - ../test/CUTE80/lock.mdb
check_validity: true
